First tests of web extension
Started to rework my extension for use as a web extension. This first batch of work is broken and should not be used in real environments.
- need to work on filtering output files
- sass errors as below (need to investigate)
```
Compilation Error
Error: Error: Illegal invocation
```